title: MiguelMR
description: "Este blog sera para ir dejando writeups de maquinas de CTF"
author:
  name: "Miguel Marin Rivera"
  email: ""
  url: "https://mykemr.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Miguel Marin Rivera"
year : "2024"
